SELECT * FROM tajwar.products;
INSERT INTO products VALUES (1, 'iPhone', 'Apple', 500.00, 'USA');
INSERT INTO products VALUES (2, 'Juice', 'Pran', 30.00, 'Bangladesh');
INSERT INTO products VALUES (3, 'Dettol', 'ACI', 60.00, 'Pakistan');
INSERT INTO products VALUES (4, 'Lipstick', 'MAC', 0.40, 'Italy');
INSERT INTO products VALUES (5, 'Laptop', 'HP', 600.00, 'USA');
INSERT INTO products VALUES (6, 'Shirt', 'Arong', 200.00, 'Bangladesh');
INSERT INTO products VALUES (7, 'Biscuit', 'Oreo', 70.00, 'India');
INSERT INTO products VALUES (8, 'Soft drink', 'Mojo', 2.00, 'Bangladesh');
INSERT INTO products VALUES (9, 'Watch', 'Rolex', 50.00, 'Switzerland');
INSERT INTO products VALUES (10, 'T-shirt', 'Gucci', 60.00, 'UK');
INSERT INTO products VALUES (11, 'Fridge', 'Walton', 400.00, 'Bangladesh');
INSERT INTO products VALUES (12, 'Medicine', 'ACI', 5.00, 'Bangladesh');
INSERT INTO products VALUES (13, 'Water', 'Pran', 5.00, 'Bangladesh');
INSERT INTO products VALUES (14, 'Oil', 'Fresh', 40.00, 'Bangladesh');
INSERT INTO products VALUES (15, 'Doi', 'Arong', 70.00, 'Bangladesh');
INSERT INTO products VALUES (16, 'Readymix food', 'Radhuni', 30.00, 'Bangladesh');
INSERT INTO products VALUES (17, 'Electronics', 'Jamuna Group', 600.00, 'Bangladesh');
INSERT INTO products VALUES (18, 'Tank', 'Gazi', 400.00, 'Bangladesh');
INSERT INTO products VALUES (19, 'Shampoo', 'Clear Men', 2.00, 'India');
INSERT INTO products VALUES (20, 'Soap', 'Dove', 5.00, 'USA');
INSERT INTO products VALUES (21, 'Ata', 'Teer', 20.00, 'Bangladesh');
INSERT INTO products VALUES (22, 'Powder milk', 'Dano', 5.00, 'India');
INSERT INTO products VALUES (23, 'TV', 'Minister', 600.00, 'Bangladesh');
INSERT INTO products VALUES (24, 'Shoes', 'Apex', 60.00, 'Bangladesh');
INSERT INTO products VALUES (25, 'Rod/steel', 'GPH Ispat', 500.00, 'Bangladesh');
INSERT INTO products VALUES (26, 'LED', 'BD Lamps', 60.00, 'Bangladesh');
INSERT INTO products VALUES (27, 'Ticket', 'Shohoz', 40.00, 'Bangladesh');
INSERT INTO products VALUES (28, 'Furniture', 'Kakoli', 700.00, 'Bangladesh');
INSERT INTO products VALUES (29, 'Plastic', 'RFL', 700.00, 'Bangladesh');
INSERT INTO products VALUES (30, 'Bike', 'Apache', 7000.00, 'India');
INSERT INTO products VALUES (31, 'Chocolate', 'KitKat', 50.00, 'USA');
INSERT INTO products VALUES (32, 'Chanachur', 'Annesha', 5.00, 'Bangladesh');
INSERT INTO products VALUES (33, 'Snaplens X', 'Optiware Inc', 70.00, 'UK');
INSERT INTO products VALUES (34, 'Charger', 'Zaptek', 60.00, 'UK');
INSERT INTO products VALUES (35, 'Sprite', 'Coca Cola', 20.00, 'USA');
INSERT INTO products VALUES (36, 'Snickers', 'Mars Inc', 50.00, 'Spain');
INSERT INTO products VALUES (37, 'KitKat', 'Nestle', 69.00, 'USA');
INSERT INTO products VALUES (38, 'Dove Soap', 'Unilever', 70.00, 'USA');
INSERT INTO products VALUES (39, 'Chips', 'Nestle', 20.00, 'Spain');
INSERT INTO products VALUES (40, 'Pepsi', 'Coca Cola', 30.00, 'USA');
INSERT INTO products VALUES (41, 'Lipstick', 'Unilever', 500.00, 'UK');
INSERT INTO products VALUES (42, 'Eye Liner', 'Unilever', 609.00, 'UK');
INSERT INTO products VALUES (43, 'Eye Shadow', 'Unilever', 700.00, 'UK');
INSERT INTO products VALUES (44, 'Car', 'Lamborghini', 100766.00, 'Italy');
INSERT INTO products VALUES (45, 'Glass', 'Nasir', 70.00, 'Bangladesh');
INSERT INTO products VALUES (46, 'Plate', 'Sarif Manamine', 69.00, 'Bangladesh');
INSERT INTO products VALUES (47, 'Perfume', 'Cobra', 700.00, 'India');
INSERT INTO products VALUES (48, 'Belt', 'Apex', 70.00, 'India');
INSERT INTO products VALUES (49, 'Mobile phone', 'Oppo', 700.00, 'China');
INSERT INTO products VALUES (50, 'Football', 'Deer', 60.00, 'China');
